/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sellerPack;

import adminPack.AdminControl;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author praduman09
 */
public class SellerReg extends javax.swing.JFrame {

    /**
     * Creates new form SellerReg
     */
    public SellerReg() {
        initComponents();
         this.setSize(620,850);
        this.setBounds(1050,100,620,850);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        nameTxt = new javax.swing.JTextField();
        emailTxt = new javax.swing.JTextField();
        mobileTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        addressTxt = new javax.swing.JComboBox<>();
        cityTxt = new javax.swing.JComboBox<>();
        stateTxt = new javax.swing.JComboBox<>();
        contryTxt = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 204));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Seller Registration");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 120, 320, 47);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Id");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(68, 175, 21, 32);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 252, 90, 40);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setText("Email");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 318, 63, 32);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setText("Address");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 383, 150, 32);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setText("City");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 450, 45, 32);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setText("State");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 520, 110, 32);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setText("Contry");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 587, 77, 32);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setText("Mobile");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 650, 75, 32);

        idTxt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        getContentPane().add(idTxt);
        idTxt.setBounds(257, 176, 261, 39);

        nameTxt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        getContentPane().add(nameTxt);
        nameTxt.setBounds(257, 245, 261, 39);

        emailTxt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        getContentPane().add(emailTxt);
        emailTxt.setBounds(257, 311, 261, 39);

        mobileTxt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        getContentPane().add(mobileTxt);
        mobileTxt.setBounds(257, 649, 261, 39);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Seller Registration");
        jButton1.setActionCommand("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(257, 728, 245, 41);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Registration.jpg"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 40, 560, 70);

        addressTxt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        addressTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S-900", "MIG-69", "S-529", "PNT-77", "D-659" }));
        getContentPane().add(addressTxt);
        addressTxt.setBounds(260, 374, 260, 40);

        cityTxt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        cityTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bhopal", "Indore", "Delhi", "Patna", "Mumbai", "Bangalore", "Hyderabad", "Pune", "Kolkata" }));
        getContentPane().add(cityTxt);
        cityTxt.setBounds(260, 444, 260, 40);

        stateTxt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        stateTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Madhya Pradesh", "Telangana", "Karnataka", "Maharashtra", "Bihar" }));
        getContentPane().add(stateTxt);
        stateTxt.setBounds(260, 514, 260, 40);

        contryTxt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        contryTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "India", "Australia", "Pakistan", "China", "America" }));
        getContentPane().add(contryTxt);
        contryTxt.setBounds(260, 584, 260, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/truevaluedb","root","Badal@123");
            String id=idTxt.getText().trim();
            String name=nameTxt.getText();
            String email=emailTxt.getText();
            String address=addressTxt.getSelectedItem().toString();
            String city=cityTxt.getSelectedItem().toString();
            String state=stateTxt.getSelectedItem().toString();
            String contry=contryTxt.getSelectedItem().toString();
            String mobile=mobileTxt.getText();
            String query="INSERT INTO truevaluedb.sellerreg VALUES(?,?,?,?,?,?,?,?)";
            PreparedStatement pst=con. prepareStatement(query);
            pst.setString(1,id);
            pst.setString(2,name);
            pst.setString(3,email);
            pst.setString(4,address);
            pst.setString(5,city);
            pst.setString(6,state);
            pst.setString(7,contry);
            pst.setString(8,mobile);
            int Count=pst.executeUpdate();
            if(Count!=0)
            {
                JOptionPane.showMessageDialog(this, Count+ "Seller Registration Successfully");
                new AdminControl().setVisible(true);
            }
            else
                JOptionPane.showMessageDialog(this, +Count+ "Seller Registration Failed Please Try Again");
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellerReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellerReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellerReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellerReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellerReg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> addressTxt;
    private javax.swing.JComboBox<String> cityTxt;
    private javax.swing.JComboBox<String> contryTxt;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JTextField idTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mobileTxt;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JComboBox<String> stateTxt;
    // End of variables declaration//GEN-END:variables
}
