/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminPack;
import java.sql.*;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/**
 *
 * @author praduman09
 */
public class AddCar extends javax.swing.JFrame {
    /**
     * Creates new form AddCar
     */
    public AddCar() {
        initComponents();
        this.setSize(804,850);
        this.setBounds(1050,100,804,850);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        priceTxt = new javax.swing.JTextField();
        fluetypeTxt = new javax.swing.JComboBox<>();
        regTxt = new javax.swing.JComboBox<>();
        companyTxt = new javax.swing.JComboBox<>();
        modelTxt = new javax.swing.JComboBox<>();
        variantTxt = new javax.swing.JComboBox<>();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Add car Window");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Fill Car Details");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(460, 210, 190, 32);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("Registration Year");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 300, 210, 32);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setText("Company");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 360, 140, 32);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setText("Model");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 440, 71, 32);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setText("Variant");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(100, 510, 81, 32);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setText("Fueltype");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(100, 580, 140, 32);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton1.setText("Add Values");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(430, 720, 170, 42);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Audi.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(380, 0, 355, 240);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setText("Price");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(100, 640, 90, 32);

        priceTxt.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        getContentPane().add(priceTxt);
        priceTxt.setBounds(400, 649, 230, 40);

        fluetypeTxt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        fluetypeTxt.setForeground(new java.awt.Color(255, 255, 255));
        fluetypeTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Petrol", "Diesel" }));
        getContentPane().add(fluetypeTxt);
        fluetypeTxt.setBounds(400, 570, 230, 40);

        regTxt.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        regTxt.setForeground(new java.awt.Color(255, 255, 255));
        regTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021" }));
        getContentPane().add(regTxt);
        regTxt.setBounds(400, 284, 230, 40);

        companyTxt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        companyTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acura", "Alfa Romeo", "Audi", "BMW", "Bentley", "Buick", "Ford", "GMC", "Honda", "Hyundai", "Jeep", "Kia", "Mazda", "Lotus", "Nikola", "Tesla", "ToyotaVolvo", "Suzuki" }));
        getContentPane().add(companyTxt);
        companyTxt.setBounds(400, 360, 230, 40);

        modelTxt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        modelTxt.setForeground(new java.awt.Color(255, 255, 255));
        modelTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BMW X3 M", "BMW M5", "BMW M5 Facelift", "BMW M2", "BMW X5 M", "Audi A8 L", "Audi A4", "Audi Q2", "Audi A6", "Audi RS Q8", "Audi Q8", "Maruti Suzuki Swift", "Maruti Suzuki Baleno", "Maruti Suzuki Ertiga", "Maruti Suzuki Alto", " Acura MDX", "Acura NSX" }));
        getContentPane().add(modelTxt);
        modelTxt.setBounds(400, 430, 230, 40);

        variantTxt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        variantTxt.setForeground(new java.awt.Color(255, 255, 255));
        variantTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X5 M", "3 M", "Series GT", "M2", "8 Series", "Q8", "RS7", "Q2", "Q8", "A6", "Alto", "Celerio", "S-Presso", "XL6", "MDX", "LTX", "RLX", "NSX" }));
        getContentPane().add(variantTxt);
        variantTxt.setBounds(400, 500, 230, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/truevaluedb","root","Badal@123");
            String regyear=regTxt.getSelectedItem().toString();
            String company=companyTxt.getSelectedItem().toString();
            String model=modelTxt.getSelectedItem().toString();
            String variant=variantTxt.getSelectedItem().toString();
            //String fueltype=fluetypeTxt.getText();
            String fueltype=fluetypeTxt.getSelectedItem().toString();
            String price=priceTxt.getText();
            String query="INSERT INTO truevaluedb.cardetail(regyear,company,model,variant,fueltype,price) VALUES(?,?,?,?,?,?)";
            PreparedStatement pst=con.prepareStatement(query);
            pst.setString(1, regyear);
            pst.setString(2, company);
            pst.setString(3, model);
            pst.setString(4, variant);
            pst.setString(5, fueltype);
            pst.setString(6, price);
            int count=pst.executeUpdate();
            if(count!=0)
            {
                JOptionPane.showMessageDialog(this,count+" "+"Car Value Added");
               /* new FiindTrueValue().setVisible(true);
                this.setVisible(false);*/
                new AdminControl().setVisible(true);
                this.setVisible(false);
            }
           else
                JOptionPane.showMessageDialog(this,count+" "+"Car Value Added Failed");
          //  fluetypeTxt.setText("");
            
            
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> companyTxt;
    private javax.swing.JComboBox<String> fluetypeTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> modelTxt;
    private javax.swing.JTextField priceTxt;
    private javax.swing.JComboBox<String> regTxt;
    private javax.swing.JComboBox<String> variantTxt;
    // End of variables declaration//GEN-END:variables
}
