/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminPack;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author praduman09
 */
public class AdminUpdate extends javax.swing.JFrame {

    /**
     * Creates new form AdminUpdate
     */
    public AdminUpdate() {
        initComponents();
        this.setSize(704,670);
        this.setBounds(1050,100,704,670);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        passTxt = new javax.swing.JPasswordField();
        updateBtn = new javax.swing.JButton();
        nameTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Update Window");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("UPDATE ADMIN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 150, 310, 47);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Enter Update User Id");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(48, 299, 260, 32);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("Enter Set User Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(48, 387, 250, 32);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setText("Enter Set User Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(48, 480, 290, 32);

        idTxt.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        idTxt.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(idTxt);
        idTxt.setBounds(388, 288, 275, 43);

        passTxt.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        passTxt.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(passTxt);
        passTxt.setBounds(388, 469, 275, 43);

        updateBtn.setBackground(new java.awt.Color(0, 0, 255));
        updateBtn.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("UPDATE");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(updateBtn);
        updateBtn.setBounds(450, 560, 132, 42);

        nameTxt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        nameTxt.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(nameTxt);
        nameTxt.setBounds(388, 386, 275, 43);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Update.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(370, 20, 310, 230);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
         try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/truevaluedb","root","Badal@123");
            String name=nameTxt.getText();
            String pass=new String(passTxt.getPassword());
            String id=idTxt.getText();
            String query="UPDATE truevaluedb.adminlogin SET username=?,password=? WHERE id=?";
            PreparedStatement pst=con.prepareStatement(query);
            pst.setString(1,name);
            pst.setString(2,pass);
            pst.setString(3,id);
            int status=pst.executeUpdate();
            if(status!=0)
            {
                JOptionPane.showMessageDialog(this, status+"Admin Updated Successfull");
               // new AdminControl().setVisible(true);
                //this.setVisible(false);
            }
            else
            JOptionPane.showMessageDialog(this, status+"Admin Updated Failed");
        new AdminControl().setVisible(true);
        this.setVisible(false);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JPasswordField passTxt;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
