/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminPack;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author praduman09
 */
public class CarRegSell extends javax.swing.JFrame {
    
    /**
     * Creates new form Carregsale
     */
    public CarRegSell() {
        initComponents();
        this.setSize(1197,910);
        this.setBounds(720,50,1250,1000);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        selleridTxt = new javax.swing.JTextField();
        regnumberTxt = new javax.swing.JTextField();
        minpriceTxt = new javax.swing.JTextField();
        maxpriceTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        actualpriceTxt = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        regyearTxt = new javax.swing.JComboBox<>();
        companyTxt = new javax.swing.JComboBox<>();
        modelTxt = new javax.swing.JComboBox<>();
        variantTxt = new javax.swing.JComboBox<>();
        fueltypeTxt = new javax.swing.JComboBox<>();
        carnumberTxt = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("RegYear");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 50, 130, 32);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Company");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 110, 109, 32);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Model");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 190, 71, 32);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Variant");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 260, 130, 32);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Fueltype");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 320, 99, 32);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Sellerid");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 390, 87, 32);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Carnumber");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 460, 150, 32);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Regnumber");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 520, 133, 32);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Minprice");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 600, 100, 32);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Maxprice");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 670, 120, 32);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel11.setText("CAR SELLER REGISTRATION");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(50, 10, 350, 32);

        selleridTxt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        getContentPane().add(selleridTxt);
        selleridTxt.setBounds(220, 390, 190, 40);

        regnumberTxt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        getContentPane().add(regnumberTxt);
        regnumberTxt.setBounds(220, 530, 190, 37);

        minpriceTxt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        getContentPane().add(minpriceTxt);
        minpriceTxt.setBounds(220, 600, 190, 38);

        maxpriceTxt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        getContentPane().add(maxpriceTxt);
        maxpriceTxt.setBounds(220, 670, 190, 40);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("TRUEVALUE CAR");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(650, 220, 410, 47);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CarSell.jpg"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(440, 0, 760, 600);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sell Car");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(520, 650, 170, 50);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("Actual Price");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(20, 740, 138, 32);

        actualpriceTxt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        getContentPane().add(actualpriceTxt);
        actualpriceTxt.setBounds(220, 740, 190, 40);

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Truevalue");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(820, 660, 150, 41);

        regyearTxt.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        regyearTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021" }));
        getContentPane().add(regyearTxt);
        regyearTxt.setBounds(220, 50, 190, 40);

        companyTxt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        companyTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acura", "Alfa Romeo", "Audi", "BMW", "Bentley", "Buick", "Ford", "GMC", "Honda", "Hyundai", "Jeep", "Kia", "Mazda", "Lotus", "Nikola", "Tesla", "ToyotaVolvo", "Suzuki" }));
        getContentPane().add(companyTxt);
        companyTxt.setBounds(220, 120, 190, 40);

        modelTxt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        modelTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BMW X3 M", "BMW M5", "BMW M5 Facelift", "BMW M2", "BMW X5 M", "Audi A8 L", "Audi A4", "Audi Q2", "Audi A6", "Audi RS Q8", "Audi Q8", "Maruti Suzuki Swift", "Maruti Suzuki Baleno", "Maruti Suzuki Ertiga", "Maruti Suzuki Alto", " Acura MDX", "Acura NSX", " " }));
        getContentPane().add(modelTxt);
        modelTxt.setBounds(220, 190, 190, 40);

        variantTxt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        variantTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X5 M", "3 M", "Series GT", "M2", "8 Series", "Q8", "RS7", "Q2", "Q8", "A6", "Alto", "Celerio", "S-Presso", "XL6", "MDX", "LTX", "RLX", "NSX" }));
        getContentPane().add(variantTxt);
        variantTxt.setBounds(220, 250, 190, 40);

        fueltypeTxt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        fueltypeTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diesel", "Petrol" }));
        getContentPane().add(fueltypeTxt);
        fueltypeTxt.setBounds(220, 320, 190, 40);

        carnumberTxt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        carnumberTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MPcs4879", "MPit12458", "MP847905", "GUG7849", "GUG4879", " " }));
        getContentPane().add(carnumberTxt);
        carnumberTxt.setBounds(220, 460, 190, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/truevaluedb","root","Badal@123");
            String regyear=regyearTxt.getSelectedItem().toString().trim();
            String company=companyTxt.getSelectedItem().toString();
            String model=modelTxt.getSelectedItem().toString();
            String variant=variantTxt.getSelectedItem().toString();
            String fueltype=fueltypeTxt.getSelectedItem().toString();
            String sellerid=selleridTxt.getText();
            String carnumber=carnumberTxt.getSelectedItem().toString();
            String regnumber=regnumberTxt.getText();
            double minprice=Double.parseDouble(minpriceTxt.getText());
            double maxprice=Double.parseDouble(maxpriceTxt.getText());
            double actualprice=Double.parseDouble(actualpriceTxt.getText());
            String query="INSERT INTO truevaluedb.carvalue VALUES(?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst=con. prepareStatement(query);
            pst.setString(1,regyear);
            pst.setString(2,company);
            pst.setString(3,model);
            pst.setString(4,variant);
            pst.setString(5,fueltype);
            pst.setString(6,sellerid);
            pst.setString(7,carnumber);
            pst.setString(8,regnumber);
            pst.setDouble(9,minprice);
            pst.setDouble(10,maxprice);
            pst.setDouble(11,actualprice);
            int Count=pst.executeUpdate();
            if(Count!=0)
            {
                JOptionPane.showMessageDialog(this, Count+ "Car Sell Successfully");
                
                new AdminControl().setVisible(true);
            }
            else
                JOptionPane.showMessageDialog(this, +Count+ "Car Sell Failed Please Another Car Try Again");
                
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new FiindTrueValue().setVisible(true);
       //this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarRegSell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarRegSell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarRegSell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarRegSell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarRegSell().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField actualpriceTxt;
    private javax.swing.JComboBox<String> carnumberTxt;
    private javax.swing.JComboBox<String> companyTxt;
    private javax.swing.JComboBox<String> fueltypeTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField maxpriceTxt;
    private javax.swing.JTextField minpriceTxt;
    private javax.swing.JComboBox<String> modelTxt;
    private javax.swing.JTextField regnumberTxt;
    private javax.swing.JComboBox<String> regyearTxt;
    private javax.swing.JTextField selleridTxt;
    private javax.swing.JComboBox<String> variantTxt;
    // End of variables declaration//GEN-END:variables
}
