/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminPack;

import javax.swing.JOptionPane;

/**
 *
 * @author praduman09
 */
public class FiindTrueValue extends javax.swing.JFrame {

    /**
     * Creates new form FiindTrueValue
     */
    public FiindTrueValue() {
        initComponents();
        this.setSize(670,590);
        this.setBounds(1100,100,670,590);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        actTxt = new javax.swing.JTextField();
        kmTxt = new javax.swing.JTextField();
        yearTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TrueValue Window");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Find Truevalue For Car");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 20, 450, 47);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Enter Actual Price For Car");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 150, 298, 32);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("Running  Kilometres Car");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 250, 282, 32);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setText("How Many Years Car Use");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 370, 286, 32);

        actTxt.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        getContentPane().add(actTxt);
        actTxt.setBounds(410, 150, 191, 40);

        kmTxt.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        getContentPane().add(kmTxt);
        kmTxt.setBounds(410, 250, 191, 40);

        yearTxt.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        getContentPane().add(yearTxt);
        yearTxt.setBounds(410, 360, 191, 40);

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Find Truevalue");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(410, 470, 206, 42);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/True.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 660, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       double actualprice;
        double newpricekm;
        int price=Integer.parseInt(actTxt.getText());
        int km=Integer.parseInt(kmTxt.getText());
        int year=Integer.parseInt(yearTxt.getText());
        if(km<=50000)
     {
        
         actualprice=price-price*0.02;
         actualprice=actualprice-price*0.1;
        JOptionPane.showMessageDialog(this, "Your Actual price=>"+actualprice); 
     }
     else if(km<=100000)
     {
         actualprice=price-price*0.04;
         actualprice=actualprice-price*0.2;
         JOptionPane.showMessageDialog(this, "Your Actual price=>"+actualprice);   
     }
     else if(km<=150000)
     {
         actualprice=price-price*0.06;
         actualprice=actualprice-price*0.3;
       JOptionPane.showMessageDialog(this, "Your Actual price=>"+actualprice);      
     }
     else if(km<=150000)
     {
         actualprice=price-price*0.08;
         actualprice=actualprice-price*0.4;
        JOptionPane.showMessageDialog(this, "Your Actual price=>"+actualprice);     
     }
     else if(km<=200000)
     {
         actualprice=price-price*0.1;
         actualprice=actualprice-price*0.5;
        JOptionPane.showMessageDialog(this, "Your Actual price=>"+actualprice);        
     }
     else if(km<=250000)
     {
         actualprice=price-price*0.12;
         actualprice=actualprice-price*0.6;
         //System.out.println("Actual price=>"+actualprice); 
         JOptionPane.showMessageDialog(this, "Your Actual price=>"+actualprice); 
     }
     else
         JOptionPane.showMessageDialog(this, "Your Car Is Expire Now"); 
        this.setVisible(false);
       new CarRegSell().setVisible(true);
      
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FiindTrueValue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FiindTrueValue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FiindTrueValue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FiindTrueValue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FiindTrueValue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField actTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField kmTxt;
    private javax.swing.JTextField yearTxt;
    // End of variables declaration//GEN-END:variables
}
