/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminPack;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author praduman09
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setSize(610,578);
        this.setBounds(500,200,610,578);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameTxt = new javax.swing.JTextField();
        passTxt = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Login");
        getContentPane().setLayout(null);

        nameTxt.setBackground(new java.awt.Color(255, 0, 0));
        nameTxt.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        nameTxt.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(nameTxt);
        nameTxt.setBounds(80, 340, 440, 50);

        passTxt.setBackground(new java.awt.Color(255, 0, 0));
        passTxt.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        passTxt.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(passTxt);
        passTxt.setBounds(80, 400, 440, 50);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(80, 460, 110, 60);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("ADMIN LOGIN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 290, 190, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Adminlogin.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 0, 230, 260);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Login.gif"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 270, 630, 280);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/truevaluedb","root","Badal@123");
            String name=nameTxt.getText().trim();
            String pass=new String(passTxt.getPassword());
            String query="SELECT * FROM truevaluedb.adminlogin WHERE username=? and password=?";
            PreparedStatement pst=con.prepareStatement(query);
            pst.setString(1,name);
            pst.setString(2,pass);
            ResultSet rst=pst.executeQuery();
            if(rst.next())
            {
                JOptionPane.showMessageDialog(this,"Login SuccessFully");
                new AdminControl().setVisible(true);
                this.setVisible(false);
            }
            else
                JOptionPane.showMessageDialog(this,"Login Failed,Try Again");
            nameTxt.setText("");
            passTxt.setText("");
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JPasswordField passTxt;
    // End of variables declaration//GEN-END:variables
}
